# NOTE: this file contains the dependencies sufficient for local testing.
# The official runtime during the challenge had other dependencies; see
# https://github.com/drivendataorg/pets-prize-challenge-runtime/blob/main/runtime/environment-gpu.yml

name: condaenv
channels:
  - conda-forge
dependencies:
  - cryptography=38.0.4
  - nvidia::cuda-nvcc=12.0.76
  - dm-haiku=0.0.8
  - graph-tool=2.45
  - imbalanced-learn=0.10.0
  - jax=0.3.20
  - keras=2.10.0
  - loguru=0.6.0
  - mkl=2022.1.0
  - numba=0.56.2
  - numpy=1.23.3
  - opacus=1.2.0
  - optax=0.1.3
  - pandas=1.4.4
  - pip=22.2.2
  - phe=1.5.0
  - pytest=7.1.3
  - python=3.9.13
  - python-igraph=0.10.2
  - pytorch-gpu=1.12.1
  # - pytorch::pytorch=1.13.1
  - pytorch-lightning=1.7.6
  - rsa=4.7.2
  - scikit-learn=1.1.2
  - scipy=1.9.1
  - tensorflow-gpu=2.10.0
  - tqdm=4.64.1
  - xgboost=1.7.1
  - pip:
      - flwr[simulation]==1.1.0
      - gower==0.1.2
      - interpret==0.3.0
      - tensorflow_privacy==0.7.3
      - tensorflow-probability==0.15.0
